services:
  - type: web
    name: cocobebe-backend
    env: node
    buildCommand: npm install
    startCommand: npm run dev
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cocobebe
          property: connectionString
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
